$(document).ready(function(){
	$('#stu_reg').hide();
	$('#emp_reg').hide();
	$('#visitor').hide();
	$('#stu_slip').hide();
	$('#ost').hide();
	$('.ctd').hide();
	$('#contd').hide();
	$('#bef').hide();
	$('#bif').hide();
	$('#brf').hide();
	$('#mef').hide();
	$('#bsf').hide();
	$('#member_filter_form').hide();
	$('#manage_member_form').hide();
	$('#search_book_record').hide();
	$('#employee_duty_allocation').hide();
	

	$('#srf').on('click',function(){
		$('#stu_reg').show();
		$('#emp_reg').hide();
		$('#visitor').hide();
		$('#ost').hide();
	});
	$('#erf').on('click',function(){
		$('#emp_reg').show();
		$('#stu_reg').hide();
		$('#visitor').hide();
		$('#ost').hide();
	});
	$('#vlnk').on('click',function(){
		$('#visitor').show();
		$('#emp_reg').hide();
		$('#stu_reg').hide();
		$('#ost').hide();
	});
	$('#ostlnk').on('click',function(){
		$('#ost').show();
		$('#visitor').hide();
		$('#emp_reg').hide();
		$('#stu_reg').hide();
	});
	$('#con').on('change',function(){
		if($(this).val() === "cont")
		{
			$('.ctd').show();
			$('#contd').show();
		}
		else
		{
			$('.ctd').hide();
			$('#contd').hide();
		}
	});


	/*Library Section*/
	$('#logbtn').on('click',function(){
		$('#libnav').show();
		$('#lib_image').hide();
		$('#search_book_record').hide();
		$('#mef').hide();
		$('#bef').hide();
		$('#bif').hide();
		$('#brf').hide();
		$('#bsf').hide();
	});
	$('#memlnk').on('click',function(){
		$('#libnav').show();
		$('#mef').show();
		$('#lib_image').hide();
		$('#member_filter_form').hide();
		$('#manage_member_form').hide();
		$('#search_book_record').hide();
		$('#bef').hide();
		$('#bif').hide();
		$('#brf').hide();
		$('#bsf').hide();
	});
	$('#etylnk').on('click',function(){
		$('#libnav').show();
		$('#lib_image').hide();
		$('#search_book_record').hide();
		$('#member_filter_form').hide();
		$('#manage_member_form').hide();
		$('#bef').show();
		$('#bif').hide();
		$('#brf').hide();
		$('#bsf').hide();
		$('#mef').hide();
	});
	$('#isslnk').on('click',function(){
		$('#libnav').show();
		$('#lib_image').hide();
		$('#search_book_record').hide();
		$('#member_filter_form').hide();
		$('#manage_member_form').hide();
		$('#bef').hide();
		$('#bif').show();
		$('#brf').hide();
		$('#bsf').hide();
		$('#mef').hide();
	});
	$('#retlnk').on('click',function(){
		$('#libnav').show();
		$('#lib_image').hide();
		$('#search_book_record').hide();
		$('#member_filter_form').hide();
		$('#manage_member_form').hide();
		$('#bef').hide();
		$('#bif').hide();
		$('#brf').show();
		$('#bsf').hide();
		$('#mef').hide();
	});
	$('#serlnk').on('click',function(){
		$('#libnav').show();
		$('#lib_image').hide();
		$('#search_book_record').show();
		$('#member_filter_form').hide();
		$('#manage_member_form').hide();
		$('#bef').hide();
		$('#bif').hide();
		$('#brf').hide();
		$('#bsf').show();
		$('#mef').hide();
	});

	// manage_member_setting show manage member form
	$('#manage_member_lnk').on('click',function(){
		$('#member_filter_form').show();
		$('#manage_member_form').show();
		$('#lib_image').hide();
		$('#search_book_record').hide();
		$('#mef').hide();
		$('#bef').hide();
		$('#bif').hide();
		$('#brf').hide();
		$('#bsf').hide();
	});

	$('#emp_duty_alloc').on('click',function(){
		$('#employee_duty_allocation').show();
	});
});